version: '3.3'
services:
  gotify:
    image: gotify/server
    container_name: gotify
    restart: always
    volumes:
      - /docker/gotify:/app/data 
    ports:
      - 80:80 
    environment:
       - TZ=Europe/London
