services:
  glances:
    container_name: glances
    image: nicolargo/glances:latest
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
    pid: host
#   network_mode: host
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/os-release:/etc/os-release:ro
    environment:
      - "GLANCES_OPT=-w"

# Notes
# network host, port 61208
