services:
  influxdb:
    image: influxdb
    container_name: InfluxDB
    ports:
      - 8086:8086
    volumes:
      - /docker/influxdb/data:/var/lib/influxdb2
      - /docker/influxdb/config:/etc/influxdb2
    restart: always
