services:
  filezilla:
    image: lscr.io/linuxserver/filezilla:latest
    container_name: FileZilla
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /docker/filezilla:/config
      - /docker/nas:/NAS
    ports:
      - 3300:3000
      - 3301:3001
    restart: unless-stopped
