version: "3.3"
services:
  guacamole:
    container_name: guacamole
    image: abesnier/guacamole
    restart: always
    ports:
      - 8080:8080
    environment:
      - EXTENSIONS=auth-ldap,auth-duo
    volumes:
      - /docker/guacamole/config:/config
