version: "3.8"
services:
  wg-easy:
    environment:
      # ⚠️  Required:
      - WG_HOST=domain.com
      - PASSWORD=nVc9BtNxTBNd5VSWETr8bE
      - WG_DEFAULT_ADDRESS=172.1.0.x
      - WG_DEFAULT_DNS=192.178.0.2
      - WG_ALLOWED_IPS=0.0.0.0/0
      # Optional:
      # - WG_PORT=51820
      # - WG_MTU=1420
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - /docker/wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
