services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - APP_KEY=xxx
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE=0 */6 * * *
      - SPEEDTEST_SERVERS=23389, 62486, 50235
      - PRUNE_RESULTS_OLDER_THAN=30
#     - DB_HOST= #optional
#     - DB_PORT= #optional
#     - DB_DATABASE= #optional
#     - DB_USERNAME= #optional
#     - DB_PASSWORD= #optional
#     - DISPLAY_TIMEZONE=Etc/UTC #optional
    volumes:
      - /docker/speedtest-tracker/data:/config
    ports:
      - 8480:80
    restart: unless-stopped
